In [1]:
import pandas as pd
import pickle

In [69]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder

In [70]:
df = pd.read_csv("houses.csv")
df

     size  bedrooms  bathrooms location  price_rwf
0    1200         3          2   Gasabo   65000000
1    1500         4          3   Gasabo   91000000
2     900         2          1     Huye   39000000
3    2000         5          4  Musanze  130000000
4    1700         4          3   Rubavu  104000000
..    ...       ...        ...      ...        ...
171  1800         4          3   Rusizi  117000000
172  1200         3          2   Rusizi   79300000
173  1300         3          2  Rutsiro   53300000
174  1600         4          3  Rutsiro   67600000
175  1000         2          1  Rutsiro   41600000

[176 rows x 5 columns]

In [71]:
encoder = LabelEncoder()
df["location"]=encoder.fit_transform(df["location"])
df

     size  bedrooms  bathrooms  location  price_rwf
0    1200         3          2         3   65000000
1    1500         4          3         3   91000000
2     900         2          1         7   39000000
3    2000         5          4        14  130000000
4    1700         4          3        24  104000000
..    ...       ...        ...       ...        ...
171  1800         4          3        27  117000000
172  1200         3          2        27   79300000
173  1300         3          2        28   53300000
174  1600         4          3        28   67600000
175  1000         2          1        28   41600000

[176 rows x 5 columns]

In [72]:
x = df[['size', 'bedrooms', 'bathrooms', 'location']]
y = df['price_rwf']

In [73]:
print(x.shape, y.shape)

(176, 4) (176,)

In [74]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [75]:
model=LinearRegression()

In [76]:
model.fit(x_train,y_train)

LinearRegression()

In [77]:
predictions=model.predict(x_test)

In [78]:
print(predictions)

[3.92095071e+07 7.86602523e+07 1.73589239e+07 8.10472361e+07
 3.03015822e+08 8.61990821e+07 6.43682781e+07 6.23094657e+07
 1.78164378e+07 3.53008601e+07 1.27469734e+08 2.77123232e+07
 1.63628617e+08 2.26598916e+07 7.05644943e+07 5.88385535e+07
 1.96662723e+07 3.25857050e+07 3.55296170e+07 3.43858324e+07
 1.12750174e+08 1.21233959e+08 8.98789721e+07 5.65509842e+07
 2.51959969e+07 7.10417873e+07 5.76947688e+07 8.45480764e+07
 9.42948401e+07 8.16041643e+07 4.14174411e+07 2.58624886e+07
 6.18321727e+07 1.56268837e+08 3.18497270e+07 3.47936390e+07]

In [79]:
accuracy = r2_score(y_test,predictions)

In [80]:
print("model accuracy",accuracy)

model accuracy 0.9414856873027765

In [81]:
pickle.dump(model,open("house_model.pkl", "wb"))
print("Model saved successfully")

Model saved successfully

In [82]:
pickle.dump(encoder,open("location_encoder.pkl","wb"))
print("model saved successfully")

model saved successfully